# Site settings
title: Charlie Tran
author: Charlie Tran
email:
description: >-
baseurl: ""
url: "https://charlietran.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: charlietran
github_username:  charlietran
twitter:
  username: charlietran
  card: summary
  creator: charlietran

excerpt_separator: <!--more-->

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed

include:
  - _redirects
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - serve
  - generate-resume-pdf
  - CNAME
